[green_agent]
agentbeats_id = "019bfe70-eb34-7651-9bcd-f58389d104c5"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "Activa"
env = {}

[config]
domain = "retail"
num_rounds = 2
