[green_agent]
image = "ghcr.io/christian-templeton/contempletiva-agent:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
agentbeats_id = ""
name = "Activa"
image = ""
env = {}

[[participants]]
agentbeats_id = ""
name = "Contempletiva"
image = ""
env = {}

[config]
topic = "What will we do if AI automates labor?"
num_rounds = 2
